### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Akul2010**
I made a README for it. Please continue writing this, I am interested in this project. Thank you!

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
There are no changes

**Comment by Akul2010** [comment]
I thought I added a README, but apparently, I didn't. So, I just created one. The point of the README is really just to explain the code so that people can contribute with ease. (They don't have to figure everything out by themselves)

**Comment by 3kh0** [comment]
Ok, it seems like the pull bot messed up the pull request, so remake your changes

**Comment by Akul2010** [comment]
Can I get write access? I'd just like to write a README and fix some other things without the pull bot messing it up. I have made the README three times already.

**Pull request merged**
